[package]
name = "samvad-grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.4"
prost-reflect = {version = "0.16.5", default-features = false, features = ["serde", "derive"] }
tonic = {version = "0.14.6", default-features = false, features = ["transport"] }
ts-rs = { workspace = true }
tokio = { workspace = true }
protox = "0.9.1"
serde_json = { workspace = true }
http = "1.5.0"
