// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeyAuth = { key: string, value: string, addTo: ApiKeyTarget, };

export type ApiKeyTarget = "header" | "query";

export type ApiRequest = { id: string, collectionId: string, folderId: string | null, name: string, method: HttpMethod, url: string, params: Array<KeyValueRow>, headers: Array<KeyValueRow>, cookies: Array<CookieRow>, auth: AuthConfig, body: RequestBody, };

export type ApiResponse = { status: number, statusText: string, timeMs: bigint, sizeBytes: bigint, headers: { [key in string]: string }, cookies: Array<CookieRow>, body: string, };

export type AppSettings = { followRedirects: boolean, maxRedirects: number, 
/**
 * When `false`, the HTTP client is built with
 * `danger_accept_invalid_certs(true)` — i.e. self-signed / invalid
 * certs are accepted. Named for clarity in the UI ("Validate SSL
 * certificates" toggle) rather than mirroring reqwest's "danger_*"
 * naming directly.
 */
verifySslCertificates: boolean, timeoutMs: bigint, userAgent: string, proxyUrl: string | null, };

export type AuthConfig = { type: AuthType, basic: BasicAuth | null, bearer: BearerAuth | null, apiKey: ApiKeyAuth | null, };

/**
 * Persistent auth state saved to `auth.yaml`.
 */
export type AuthState = { user: User | null, tokens: AuthTokens | null, };

export type AuthTokens = { accessToken: string, refreshToken: string | null, idToken: string | null, expiresIn: bigint, expiresAt: bigint, };

export type AuthType = "none" | "basic" | "bearer" | "apiKey";

export type BasicAuth = { username: string, password: string, };

export type BearerAuth = { token: string, };

export type BodyMode = "json" | "form-data" | "urlencoded" | "raw" | "multipart";

export type Collection = { id: string, workspaceId: string, name: string, sortOrder: bigint, };

/**
 * Nested tree shape sent to the frontend for rendering the sidebar in
 * one shot, rather than making it re-assemble flat rows.
 */
export type CollectionTree = { collection: Collection, folders: Array<FolderNode>, 
/**
 * Requests directly under the collection root (no folder).
 */
requests: Array<ApiRequest>, };

export type CookieRow = { id: string, name: string, value: string, domain: string, };

export type Environment = { id: string, workspaceId: string, name: string, sortOrder: bigint, };

export type EnvironmentVariable = { id: string, environmentid: string, key: string, value: string, enabled: boolean, isSecret: boolean, };

export type EnvironmentWithVariables = { environment: Environment, variables: Array<EnvironmentVariable>, };

export type Folder = { id: string, collectionId: string, parentFolderId: string | null, name: string, sortOrder: bigint, };

export type FolderNode = { folder: Folder, children: Array<FolderNode>, requests: Array<ApiRequest>, };

export type HistoryEntry = { id: string, requestId: string | null, name: string | null, method: HttpMethod, url: string, status: number, durationMs: bigint, createdAt: string, };

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD" | "WS" | "QUERY";

export type KeyValueRow = { id: string, key: string, value: string, enabled: boolean, };

export type PluginHook = "preRequest" | "postResponse";

/**
 * `manifest.json` shape every plugin folder must provide.
 */
export type PluginManifest = { id: string, name: string, version: string, description: string, 
/**
 * Path to the JS entry file, relative to the plugin's own folder.
 */
entry: string, 
/**
 * Which lifecycle hooks this plugin implements. The entry script is
 * expected to define a top-level function per hook it declares here
 * — `preRequest(ctx)` and/or `postResponse(ctx)`.
 */
hooks: Array<PluginHook>, };

export type PluginRecord = { id: string, name: string, version: string, description: string, enabled: boolean, installPath: string, hooks: Array<PluginHook>, installedAt: string, };

export type RequestBody = { mode: BodyMode | null, raw?: string, formData?: Array<KeyValueRow>, urlEncoded?: Array<KeyValueRow>, files?: Array<UploadedFile>, };

export type Theme = { id: string, name: string, isBuiltin: boolean, tokens: ThemeTokens, };

/**
 * Mirrors the `@theme` tokens in the frontend's `src/index.css`. Custom
 * themes are just a different value set for the same keys — the
 * frontend applies a theme by writing these as CSS custom properties
 * on `:root` at runtime (see commands/themes.rs doc comment).
 */
export type ThemeTokens = { colorBg: string, colorPanel: string, colorPanelRaised: string, colorBorder: string, colorBorderMuted: string, colorTextPrimary: string, colorTextSecondary: string, colorTextMuted: string, colorPrimary: string, colorPrimaryHover: string, colorSecondary: string, colorSuccess: string, colorError: string, colorWarning: string, radiusMd: string, radiusLg: string, fontSans: string, fontMono: string, };

export type UploadedFile = { id: string, name: string, sizeBytes: bigint, 
/**
 * Absolute filesystem path, populated by the `pick_files` command
 * (native file dialog), giving the backend real disk access for
 * multipart uploads.
 */
path: string, };

export type User = { sub: string, name?: string, email?: string, picture?: string, updatedAt?: string, };

export type Workspace = { id: string, name: string, createdAt: string, updatedAt: string, };

/**
 * Payload emitted over the Tauri event channel for each WS frame
 * (both sent and received).
 */
export type WsEvent = { connectionId: string, direction: string, data: string, timestamp: string, };

/**
 * A saved message template the user creates for reuse — persisted to
 * YAML alongside the request that owns it.
 */
export type WsSavedMessage = { id: string, name: string, data: string, };
