// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthTokens = { accessToken: string, refreshToken: string | null, idToken: string | null, expiresIn: bigint, expiresAt: bigint, };
